language: julia
julia:
 - release
 - nightly
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.test("BackpropNeuralNet", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BackpropNeuralNet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
